[project]
name = ""
version = ""
description = ""
authors = [
    {name = "shims94", email = "shims94@gmail.com"},
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

